# Generated by Django 3.1.4 on 2020-12-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('create_date', models.CharField(max_length=20)),
                ('emergency', models.BooleanField(null=True)),
            ],
        ),
    ]
